name: Build
on:
  release:
    types: [created]
jobs:
  execute_buildzip_script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Make ZIP files
        run: |
          echo "⚙️ Installing Composer dependencies"
          bin/composer install --no-dev --quiet --no-interaction
          echo "⚙️ Installing NPM dependencies and building"
          bin/npm install --no-progress --no-update-notifier
          bin/npm run build --no-progress --no-update-notifier
          echo "🧹 Removing unwanted files"
          sudo rm -Rf sequra/node_modules
          rm -Rf sequra/tests
          rm -Rf sequra/tests-e2e
          rm -Rf sequra/apigen
          rm -f sequra/.gitignore glue-plugins/sequra-no-address/.gitignore
          rm -f sequra/package.json
          rm -f sequra/package-lock.json
          rm -f sequra/composer.json glue-plugins/sequra-no-address/composer.json
          rm -f sequra/composer.lock glue-plugins/sequra-no-address/composer.lock
          rm -f sequra/.phpcs.xml.dist glue-plugins/sequra-no-address/.phpcs.xml.dist
          rm -f sequra/babel.config.json
          rm -f sequra/phpstan.neon glue-plugins/sequra-no-address/phpstan.neon
          rm -f sequra/phpunit.xml.dist
          rm -f sequra/playwright.config.js
          rm -f sequra/postcss.config.js
          rm -f sequra/*.log
          rm -f sequra/webpack.config.js
          echo "📦 Creating ZIP files"
          mkdir -p zip
          cd sequra
          zip -r9 ../zip/sequra.zip .
          cd ../glue-plugins/sequra-no-address
          zip -r9 ../zip/sequra-no-address.zip .
          echo "📎 Attaching ZIP files to the release"
          cd zip
          release_id=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" https://api.github.com/repos/${{ github.repository }}/releases/tags/${{ github.ref_name }} | jq -r .id)
          curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" -H "Content-Type: application/zip" --data-binary @sequra.zip "https://uploads.github.com/repos/${{ github.repository }}/releases/$release_id/assets?name=sequra-${{ github.ref_name }}.zip"
          curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" -H "Content-Type: application/zip" --data-binary @sequra-no-address.zip "https://uploads.github.com/repos/${{ github.repository }}/releases/$release_id/assets?name=sequra-no-address-${{ github.ref_name }}.zip"