name: Build
on:
  release:
    types: [created]
jobs:
  execute_buildzip_script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Execute make_zip script
        run: |
          ./bin/make_zip --branch=${{ github.ref_name }} --project=sequra --filename=sequra.zip
          ./bin/make_zip --branch=${{ github.ref_name }} --project=sequra-no-address --filename=sequra-no-address.zip
      - name: Attach ZIP file to release
        run: |
          cd zip
          release_id=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" https://api.github.com/repos/${{ github.repository }}/releases/tags/${{ github.ref_name }} | jq -r .id)
          curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" -H "Content-Type: application/zip" --data-binary @sequra.zip "https://uploads.github.com/repos/${{ github.repository }}/releases/$release_id/assets?name=sequra-${{ github.ref_name }}.zip"
          curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" -H "Content-Type: application/zip" --data-binary @sequra-no-address.zip "https://uploads.github.com/repos/${{ github.repository }}/releases/$release_id/assets?name=sequra-no-address-${{ github.ref_name }}.zip"
