name: CI

on:
  push: {}
  pull_request:
    types: [opened, synchronize, reopened]

concurrency:
  # For pull requests, cancel all currently-running jobs for this workflow
  # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#concurrency
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

env:
  # Force terminal colors. @see https://www.npmjs.com/package/colors
  FORCE_COLOR: 1

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # - name: Cache Composer dependencies
      #   uses: actions/cache@v4
      #   id: cache-composer
      #   with:
      #     path: |
      #       sequra/vendor
      #       sequra/composer.lock
      #     key: composer-${{ hashFiles('sequra/composer.json') }}

      - name: Install Composer dependencies
        # if: steps.cache-composer.outputs.cache-hit != 'true'
        run: ./bin/composer install --quiet --no-interaction

      - name: PHP 7.3 Syntax check
        if: github.event_name == 'push'
        run: bin/php-syntax-check --php=7.3

      - name: PHP 7.4 Syntax check
        if: github.event_name == 'push'
        run: bin/php-syntax-check --php=7.4

      - name: PHP 8.0 Syntax check
        if: github.event_name == 'push'
        run: bin/php-syntax-check --php=8.0

      - name: PHP 8.1 Syntax check
        if: github.event_name == 'push'
        run: bin/php-syntax-check --php=8.1

      - name: PHP 8.2 Syntax check
        if: github.event_name == 'push'
        run: bin/php-syntax-check --php=8.2

      - name: PHP 8.3 Syntax check
        if: github.event_name == 'push'
        run: bin/php-syntax-check --php=8.3

      - name: PHP 8.4 Syntax check
        if: github.event_name == 'push'
        run: bin/php-syntax-check --php=8.4

      - name: Cache NPM dependencies
        if: github.event_name == 'pull_request'
        uses: actions/cache@v4
        id: cache-npm
        with:
          path: |
            sequra/node_modules
            sequra/package-lock.json
          key: npm-${{ hashFiles('sequra/package-lock.json') }}

      - name: Install NPM dependencies
        if: github.event_name == 'pull_request' && steps.cache-npm.outputs.cache-hit != 'true'
        run: ./bin/npm install --no-progress --silent --no-update-notifier

      - name: Cache Assets
        if: github.event_name == 'pull_request'
        uses: actions/cache@v4
        id: cache-assets
        with:
          path: |
            sequra/assets/css/*.css
            sequra/assets/js/dist
          key: assets-${{ hashFiles('sequra/assets/css/scss/*.scss', 'sequra/assets/js/src/**/*.js') }}

      - name: Build Assets
        if: github.event_name == 'pull_request' && steps.cache-assets.outputs.cache-hit != 'true'
        run: ./bin/npm run build --no-progress --silent --no-update-notifier

      - name: PHPCS
        if: github.event_name == 'push'
        run: ./bin/phpcs -q

      - name: PHPStan
        if: github.event_name == 'push'
        run: ./bin/phpstan --error-format=github --no-progress

      - name: Setup Environment
        if: github.event_name == 'pull_request'
        env:
          DUMMY_ASSETS_KEY: ${{ secrets.DUMMY_ASSETS_KEY }}
          DUMMY_PASSWORD: ${{ secrets.DUMMY_PASSWORD }}
          DUMMY_SERVICE_PASSWORD: ${{ secrets.DUMMY_SERVICE_PASSWORD }}
        run: |
          cp .env.sample .env
          sed -i "s/^DUMMY_ASSETS_KEY=.*/DUMMY_ASSETS_KEY=$DUMMY_ASSETS_KEY/" .env
          sed -i "s/^DUMMY_PASSWORD=.*/DUMMY_PASSWORD=$DUMMY_PASSWORD/" .env
          sed -i "s/^DUMMY_SERVICE_PASSWORD=.*/DUMMY_SERVICE_PASSWORD=$DUMMY_SERVICE_PASSWORD/" .env
          ./setup.sh --install=0 --disable-ngrok=1

      - name: Setup Tests
        if: github.event_name == 'pull_request'
        run: docker compose exec web /usr/local/bin/setup-tests.sh

      - name: Run Tests
        if: github.event_name == 'pull_request'
        run: |
          docker compose exec web /usr/local/bin/run-tests.sh

      - name: Teardown Environment
        if: github.event_name == 'pull_request'
        run: ./teardown.sh
