name: Unit tests

on:
  pull_request:
    types: [synchronize]
    paths:
      - '**.php'

concurrency:
  group: unit-tests-${{ github.ref }}
  cancel-in-progress: true

jobs:
  phpunit:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - uses: actions/cache@v5
        id: sequra-composer-cache
        with:
          path: |
            sequra/vendor
            sequra/composer.lock
          key: sequra-composer-cache-${{ hashFiles('sequra/composer.lock') }}

      - name: Composer install
        if: steps.sequra-composer-cache.outputs.cache-hit != 'true'
        run: |
          cd sequra
          composer install --quiet --no-interaction

      - name: Setup the environment
        env:
          DUMMY_ASSETS_KEY: ${{ secrets.DUMMY_ASSETS_KEY }}
          DUMMY_PASSWORD: ${{ secrets.DUMMY_PASSWORD }}
          DUMMY_SERVICE_PASSWORD: ${{ secrets.DUMMY_SERVICE_PASSWORD }}
        run: |
          cp .env.sample .env
          sed -i.bak "s/^DUMMY_ASSETS_KEY=.*/DUMMY_ASSETS_KEY=$DUMMY_ASSETS_KEY/" .env && rm .env.bak
          sed -i.bak "s/^DUMMY_PASSWORD=.*/DUMMY_PASSWORD=$DUMMY_PASSWORD/" .env && rm .env.bak
          sed -i.bak "s/^DUMMY_SERVICE_PASSWORD=.*/DUMMY_SERVICE_PASSWORD=$DUMMY_SERVICE_PASSWORD/" .env && rm .env.bak
          ./setup.sh

      - name: Setup the tests
        run: docker compose exec web /usr/local/bin/setup-tests.sh

      - name: Run the tests
        run: docker compose exec web /usr/local/bin/run-tests.sh
      
      - name: Tear down the environment
        run: ./teardown.sh