name: Run Unit Tests

on: [push]

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the source code
        uses: actions/checkout@v4.1.4

      - name: Setup
        run: ./setup.sh

      - name: Setup Tests
        run: docker compose exec web /var/www/html/setup-tests.sh

      - name: Run Tests
        run: |
          docker compose exec web /var/www/html/run-tests.sh

      - name: Cleanup
        run: ./terminate.sh
