name: Unit tests

on:
  pull_request:
    types: [synchronize]
    paths:
      - '**.php'
  workflow_dispatch:

concurrency:
  group: unit-tests-${{ github.ref }}
  cancel-in-progress: true

jobs:
  composer:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - uses: actions/cache@v5
        id: sequra-composer-cache
        with:
          path: |
            sequra/vendor
            sequra/composer.lock
          key: sequra-composer-cache-${{ hashFiles('sequra/composer.lock') }}

      - name: Composer install
        if: steps.sequra-composer-cache.outputs.cache-hit != 'true'
        run: |
          composer install --quiet --no-interaction

  # Theres is currently no need for assets for the tests to succeed
  # hence, we are commenting this out to save CI resources but keeping
  # it here for future reference.
  # npm:
  #   runs-on: ubuntu-latest

  #   steps:
  #     - uses: actions/checkout@v6

  #     - uses: actions/cache@v5
  #       id: sequra-npm-cache
  #       with:
  #         path: |
  #           sequra/node_modules
  #           sequra/package-lock.json
  #         key: sequra-npm-cache-${{ hashFiles('sequra/package-lock.json') }}
      
  #     - name: NPM install
  #       if: steps.sequra-npm-cache.outputs.cache-hit != 'true'
  #       run: npm install --no-progress --silent --no-update-notifier

  phpunit:
    # needs: [composer, npm]
    needs: [composer]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - uses: actions/cache@v5
        id: sequra-composer-cache
        with:
          path: |
            sequra/vendor
            sequra/composer.lock
          key: sequra-composer-cache-${{ hashFiles('sequra/composer.lock') }}
      
      # Theres is currently no need for assets for the tests to succeed
      # hence, we are commenting this out to save CI resources but keeping
      # it here for future reference.
      # - uses: actions/cache@v5
      #   id: sequra-npm-cache
      #   with:
      #     path: |
      #       sequra/node_modules
      #       sequra/package-lock.json
      #     key: sequra-npm-cache-${{ hashFiles('sequra/package-lock.json') }}

      # - name: Build Assets
      #   run: bin/npm run build --no-progress --silent --no-update-notifier

      - name: Setup the environment
        env:
          DUMMY_ASSETS_KEY: ${{ secrets.DUMMY_ASSETS_KEY }}
          DUMMY_PASSWORD: ${{ secrets.DUMMY_PASSWORD }}
          DUMMY_SERVICE_PASSWORD: ${{ secrets.DUMMY_SERVICE_PASSWORD }}
        run: |
          cp .env.sample .env
          sed -i.bak "s/^DUMMY_ASSETS_KEY=.*/DUMMY_ASSETS_KEY=$DUMMY_ASSETS_KEY/" .env && rm .env.bak
          sed -i.bak "s/^DUMMY_PASSWORD=.*/DUMMY_PASSWORD=$DUMMY_PASSWORD/" .env && rm .env.bak
          sed -i.bak "s/^DUMMY_SERVICE_PASSWORD=.*/DUMMY_SERVICE_PASSWORD=$DUMMY_SERVICE_PASSWORD/" .env && rm .env.bak
          ./setup.sh

      - name: Setup the tests
        run: docker compose exec web /usr/local/bin/setup-tests.sh

      - name: Run the tests
        run: docker compose exec web /usr/local/bin/run-tests.sh